#===============================================================================
# CIS Apache Cassandra 4.0 - Hardened Configuration Template
#===============================================================================

cluster_name: cis-cluster
num_tokens: 256

authenticator: PasswordAuthenticator
authorizer: CassandraAuthorizer

rpc_address: 127.0.0.1

native_transport_port: 9042

storage_port: 7000

data_file_directories:
    - /var/lib/cassandra/data
commitlog_directory: /var/lib/cassandra/commitlog
saved_caches_directory: /var/lib/cassandra/saved_caches
hints_directory: /var/lib/cassandra/hints
