name: Debug CI Trigger

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Check
        run: |
          echo "CI is active!"
          date
          ls -R
